export const USER_lOGIN_REQUEST = "USER_lOGIN_REQUEST";
export const USER_lOGIN_SUCCESS = "USER_lOGIN_SUCCESS";
export const USER_lOGIN_FAIL = "USER_lOGIN_FAIL";
export const USER_LOGOUT = "USER_lOGIN_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
